# 语音系统设置：0（关闭）、1（原来的语音系统）、2（腾讯语音）
VoiceSystem: 0

# 发音人（仅原来的语音系统有效）
VoiceIndex: 23

# 腾讯云文字转语音配置
TencentCloudTTS:
  # 地域
  Region: ap-guangzhou
  # SecretId
  SecretId: "你的腾讯云SecretId"
  # SecretKey
  SecretKey: "你的腾讯云SecretKey"
  # 语音类型（音色 ID），包括精品音色、大模型音色与基础版复刻音色
  VoiceType: 502001
  # 语速，范围：[-2，6]，分别对应不同语速：-2代表0.6倍，-1代表0.8倍，0代表1.0倍（默认）
  Speed: 0
  # 音量大小，范围[-10，10]，对应音量大小。默认为2，代表稍高音量
  Volume: 2
  # 采样率：24000：24k（推荐），16000：16k，8000：8k
  SampleRate: 24000
  # 返回音频格式，可取值：wav，mp3（推荐），pcm
  Codec: "mp3"
